export const SET_NEWS = 'setNews'
export const SET_PROJECTS = 'setProjects'
export const SET_CURRENT_PROJECT = 'setCurrentProject'
export const SET_IS_MOBILE = 'setIsMobile'
export const SET_IS_TABLET_VIEW = 'setIsTabletView'
