site_url: https://dotyk.netlify.app/
logo_url: https://dotyk.netlify.app/icon.png

# publish_mode: editorial_workflow
backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

# Docs: https://www.netlifycms.org/docs/configuration-options/#collections
collections:
  - label: 'Site settings'
    name: 'site'
    files:
      - label: 'Info'
        name: 'info'
        file: 'assets/content/site/info.json'
        format: 'json'
        editor:
          preview: false
        fields:
          - { label: Site Name, name: sitename, widget: string, hint: 'This is used for the site title' }
          - {
              label: Site Description,
              name: sitedescription,
              widget: string,
              hint: 'This is used as descriptive text for links that link to this site',
            }
          - {
              label: Site Language,
              name: sitelang,
              widget: string,
              pattern: ['^[a-z]{2}([-])?([A-Za-z]{2})?$', 'Must match "xx" or "xx-XX" syntax (ex. "en" or "sv-SE")'],
            }
          # - { label: Site Email, name: siteemail, widget: string, required: false }
  - name: 'projects'
    label: 'Projects'
    identifier_field: title_en
    folder: 'assets/content/projects'
    create: true
    format: 'json'
    slug: '{{slug}}'
    fields:
      - { name: 'title_en', label: 'Title en', widget: 'string' , required: true , default: ''} 
      - { name: 'title_pt', label: 'Title pt', widget: 'string' , required: false , default: ''}
      - { name: 'description_en', label: 'Description en', widget: 'string' , required: false , default: ''} 
      - { name: 'description_pt', label: 'Description pt', widget: 'string' , required: false , default: ''}
      - { name: 'year' , label: 'Year', widget: 'string' , required: false }
      - { name: 'tags', label: 'Tags', widget: 'list', default: [], required: false } 
      - { name: 'thumbnail', required: false, label: 'Thumbnail Image', widget: 'image' }
      - { name: 'cover_img', required: false, label: 'Cover Image', widget: 'image' }
      - { name: 'content_en', label: 'content_en', widget: 'markdown' , required: false, default: ''} 
      - { name: 'content_pt', label: 'content_pt', widget: 'markdown' , required: false, default: ''}
      - {
          label: 'Gallery',
          name: 'gallery',
          widget: 'list',
          required: false,
          summary: '{{fields.image}}',
          field: { label: 'Image', name: 'image', widget: 'image' },
        }
      - {label: "Disabled", name: "disabled", widget: "boolean", default: false}

  - name: 'news'
    label: 'News'
    folder: 'assets/content/news'
    create: true
    format: 'json'
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
